### ISSUE TITLE
Linechart doesn't work

### ISSUE THREAD

**Issue by lmaiimv** [pstephan1187/PhantomJS-Google-Charts#1]
When I change the charttype from piechart to linechart, I get a "not an array" error.
Any idea how to resolve this?

**Comment by pstephan1187** [comment]
Can you attach your code? If I am following you correctly, that error is being returned by Google Charts because the data you are passing to the chart is not an array, but I could be wrong. You will need to attach some code for me to be able to say for sure

**Comment by lmaiimv** [comment]
Thanks for getting back to me.
I figured it out. (sorry, long night last night)
I needed to add the conversion of json to chartdata for the linechart type.
FYI, slightly different from the piechart to account for the two-d table (line chart)

<pre>
case 'LineChart':
    if(typeof jsonData.columns == 'array' || typeof jsonData.columns == 'object'){
        for(var i in jsonData.columns){
            chartData.addColumn(jsonData.columns[i], i);
        }
    }
    if(typeof jsonData.rows == 'array' || typeof jsonData.rows == 'object'){
        for(var i in jsonData.rows){
            chartData.addRows([[i, jsonData.rows[i][0], jsonData.rows[i][1]]]);
        }
    }
break;
</pre>
